export const GET_ELEMENT_DETAILS = "/docs/getDocByUniqueSlug"
export const GET_DOCS_LIST = "/docs/getUniqueSlugs/get-docs-list"
export const GET_DOCS_LIST_WITH_CODE = "/docs/getUniqueSlugs/get-docs-list-with-code"
export const SIGN_IN = "/users/login"
export const SIGN_UP = "/users/signup"